spring:
  application:
    name: EMPLOYEE-SERVICE

  config:
    import: "configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

  tracing:
    sampling:
      probability: 1.0   # 100% of requests are traced
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"